# Generated by Django 2.1.1 on 2018-11-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_url', models.CharField(max_length=200)),
                ('article_title', models.CharField(max_length=200)),
                ('article_pub_date', models.DateTimeField(verbose_name='Published date')),
            ],
        ),
    ]
